from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.units import mm


def build_pdf(path: str):
    doc = SimpleDocTemplate(
        path,
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=16 * mm,
        bottomMargin=16 * mm,
    )
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name='CodeNote', fontName='Courier', fontSize=8, leading=10, leftIndent=12, textColor='#1F2D3D'))
    styles.add(ParagraphStyle(name='BoldMono', fontName='Courier-Bold', fontSize=8.5, leading=10, textColor='#0F172A'))
    styles.add(ParagraphStyle(name='SectionHead', fontName='Helvetica-Bold', fontSize=16, leading=20, spaceAfter=8, textColor='#0B3D91'))
    styles.add(ParagraphStyle(name='SubHead', fontName='Helvetica-Bold', fontSize=11, leading=14, spaceBefore=10, spaceAfter=4, textColor='#17375E'))
    styles.add(ParagraphStyle(name='Body', fontName='Helvetica', fontSize=10.5, leading=14, spaceAfter=6, textColor='#1F2937'))

    story = []

    def add_title(title):
        story.append(Paragraph(title, styles['Title']))
        story.append(Spacer(1, 8 * mm))

    def add_section(title):
        story.append(Paragraph(title, styles['SectionHead']))

    def add_text(text):
        story.append(Paragraph(text, styles['Body']))

    def add_code(code):
        story.append(Paragraph(code, styles['CodeNote']))

    def add_bullet(text):
        story.append(Paragraph('• ' + text, styles['Body']))

    add_title('Day 4 — Day 3 to Day 4 RAG Correlation + Code Walkthrough')
    add_text('This PDF is intentionally code-focused and demo-ready. It connects the Day 3 notebook workflow to the Day 4 project code so the instructor can point to exact snippets, explain the equivalent logic, and run the same idea live in VS Code.')
    add_text('The goal is not to summarize frameworks. The goal is to show that the underlying architecture is the same: ingest documents, split them, embed them, store vectors, retrieve relevant chunks, and pass them to an LLM.')
    story.append(PageBreak())

    add_section('Page 1 — The real message: same RAG architecture, different tooling')
    add_text('Use this as the opening explanation before touching code. The notebook and the project are not different ideas; they are two implementations of the same architecture.')
    add_code('Day 3 notebook flow:')
    add_code('  SimpleDirectoryReader -> Document -> SentenceSplitter -> HuggingFaceEmbedding -> LanceDBVectorStore -> VectorStoreIndex -> query_engine')
    add_code('Day 4 project flow:')
    add_code('  src/pdf_parser.py -> src/chunker.py -> SentenceTransformerEmbeddingFunction -> Chroma collection -> src/vector_store.py.query() -> src/rag.py')
    add_text('What to say out loud: “The notebook used a high-level framework. The project does the same steps manually in Python. The architecture is the same, but the abstraction layer is different.”')
    add_text('This is the teaching point students need to understand before any code highlighting begins.')
    story.append(PageBreak())

    add_section('Page 2 — Day 3 notebook equivalent: ingestion and document preparation')
    add_text('In the notebook, you likely saw code similar to this pattern from LlamaIndex:')
    add_code('from llama_index.core import SimpleDirectoryReader, Document')
    add_code('documents = SimpleDirectoryReader("data/").load_data()')
    add_code('for doc in documents:')
    add_code('    print(doc.text[:200])')
    add_text('This corresponds directly to the project code in src/main.py and src/pdf_parser.py, where the system extracts text from PDFs and prepares it for chunking.')
    add_code('pages = extract_pages(pdf_path)')
    add_code('chunks = chunk_text(pages, source=source, chunk_size=300, overlap=50)')
    add_code('store.add_chunks(chunks)')
    add_text('What to say out loud: “The notebook loaded documents into a document abstraction. Our project loads PDF pages and converts them into chunk objects. Same step—different representation.”')
    story.append(PageBreak())

    add_section('Page 3 — Day 3 notebook equivalent: chunking with SentenceSplitter')
    add_text('In the notebook, the chunking step was likely done by LlamaIndex’s SentenceSplitter. That is the same conceptual role as src/chunker.py, which splits raw text into retrievable units.')
    add_code('from llama_index.core.node_parser import SentenceSplitter')
    add_code('splitter = SentenceSplitter(chunk_size=300, chunk_overlap=50)')
    add_code('nodes = splitter.get_nodes_from_documents(documents)')
    add_text('In Day 4, the equivalent code is here:')
    add_code('for page in pages:')
    add_code('    words = page["text"].split()')
    add_code('    end = start + chunk_size')
    add_code('    chunk_words = words[start:end]')
    add_code('    chunk_str = " ".join(chunk_words)')
    add_code('    chunks.append({')
    add_code('        "text": chunk_str,')
    add_code('        "page": page["page"],')
    add_code('        "chunk_id": chunk_id,')
    add_code('    })')
    add_code('    start = end - overlap')
    add_text('What to say out loud: “SentenceSplitter in the notebook is just a framework wrapper around the same operation we are implementing manually in src/chunker.py. Both create smaller, overlapping chunks so no fact is prematurely cut off.”')
    story.append(PageBreak())

    add_section('Page 4 — Day 3 notebook equivalent: embeddings with HuggingFaceEmbedding')
    add_text('In the notebook, the embedding step was probably done with HuggingFaceEmbedding and an IngestionPipeline. The Day 4 version is explicit in src/vector_store.py.')
    add_code('from llama_index.embeddings.huggingface import HuggingFaceEmbedding')
    add_code('embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")')
    add_code('pipeline = IngestionPipeline(transformations=[SentenceSplitter(...), embed_model], vector_store=vector_store)')
    add_text('Equivalent code in the project:')
    add_code('self.embedding_fn = embedding_functions.SentenceTransformerEmbeddingFunction(')
    add_code('    model_name="all-MiniLM-L6-v2"')
    add_code(')')
    add_code('self.collection = self.client.get_or_create_collection(')
    add_code('    name=collection_name,')
    add_code('    embedding_function=self.embedding_fn,')
    add_code('    metadata={"hnsw:space": "cosine"},')
    add_code(')')
    add_text('What to say out loud: “Both systems convert each chunk into a vector. In the notebook, the framework hides the details. In the project, we are doing the same step explicitly and storing the result in Chroma.”')
    story.append(PageBreak())

    add_section('Page 5 — Day 3 notebook equivalent: vector DB storage with LanceDB')
    add_text('In the notebook, the vector database was likely LanceDB. In the project, the equivalent is ChromaDB. The conceptual job is identical: persist the vectors so they can be searched later.')
    add_code('from llama_index.vector_stores.lancedb import LanceDBVectorStore')
    add_code('vector_store = LanceDBVectorStore(uri="./lancedb_data", table_name="docs")')
    add_text('Equivalent project code:')
    add_code('self.client = chromadb.PersistentClient(path=persist_dir)')
    add_code('self.collection = self.client.get_or_create_collection(')
    add_code('    name=collection_name,')
    add_code('    embedding_function=self.embedding_fn,')
    add_code('    metadata={"hnsw:space": "cosine"},')
    add_code(')')
    add_text('What to say out loud: “This is the storage layer. The database is where the vectorized document knowledge lives. The notebook used LanceDB; the project uses Chroma. Same job, different backend.”')
    story.append(PageBreak())

    add_section('Page 6 — Day 3 notebook equivalent: query engine and retrieval')
    add_text('This is the most important connection point. In the notebook, the framework created a query engine that retrieved top matches and sent them to the LLM. In the project, the retrieval logic is written explicitly in src/vector_store.py and orchestrated in src/rag.py.')
    add_code('index = VectorStoreIndex.from_vector_store(vector_store=vector_store, embed_model=embed_model)')
    add_code('query_engine = index.as_query_engine(response_mode="tree_summarize")')
    add_code('response = query_engine.query(question)')
    add_text('Equivalent project code:')
    add_code('results = self.collection.query(query_texts=[question], n_results=fetch_k, where=where)')
    add_code('for rank, (text, meta, dist) in enumerate(')
    add_code('    zip(results["documents"][0], results["metadatas"][0], results["distances"][0]), start=1')
    add_code('):')
    add_code('    candidates.append({')
    add_code('        "text": text,')
    add_code('        "page": meta["page"],')
    add_code('        "source": meta["source"],')
    add_code('        "distance": dist,')
    add_code('        "confidence": 1 - (dist / 2),')
    add_code('    })')
    add_text('What to say out loud: “This is the exact retrieval step. The notebook had a query engine abstraction; the project exposes the same behavior in plain Python. We are still asking the vector store for the nearest relevant passages.”')
    story.append(PageBreak())

    add_section('Page 7 — Day 3 notebook equivalent: LLM answer generation and model provider layer')
    add_text('In the notebook, the LLM was likely called through a wrapper or an inference API. In the project, the LLM is selected centrally in src/llm_config.py and the actual orchestration sits in src/rag.py.')
    add_code('llm = HuggingFaceInferenceAPI(model_name="...")')
    add_code('response = query_engine.query(question)')
    add_text('Equivalent project code:')
    add_code('raw_active_provider = (os.environ.get("ACTIVE_PROVIDER") or "").strip().lower()')
    add_code('if provider == "openrouter":')
    add_code('    return LLMSettings(')
    add_code('        name="openrouter",')
    add_code('        model=os.environ.get("OPENROUTER_MODEL") or "openai/gpt-oss-20b:free",')
    add_code('        api_key=os.environ.get("OPENROUTER_API_KEY"),')
    add_code('    )')
    add_code('SYSTEM_PROMPT = """Document-first policy..."""')
    add_text('What to say out loud: “The notebook simplified the model call. Our project makes the provider and model selection explicit, which is what makes it easier to switch between OpenRouter, Gemini, and Hugging Face in real usage.”')
    story.append(PageBreak())

    add_section('Page 8 — The conceptual continuity to repeat in class')
    add_text('Use this exact explanation live:')
    add_code('“Day 3 was a framework-based proof of concept. Day 4 is the same RAG architecture implemented as a real Python app.”')
    add_code('“The notebook used LlamaIndex, LanceDB, and a simplified query engine. The project uses custom parsing, chunking, Chroma, and explicit retrieval logic.”')
    add_code('“The logic is the same even though the APIs are different.”')
    add_text('Then say: “We are not building a different concept. We are building the same concept with different tools and more control.”')
    add_text('This is the line to anchor the teaching story and help students see continuity instead of a jump to a new project.')
    story.append(PageBreak())

    add_section('Page 9 — PDF ingestion: where the indexing starts')
    add_text('Show this live in src/main.py. This is the counterpart of the notebook’s ingestion workflow. The important idea is: read a PDF, split it into chunks, insert into vector DB.')
    add_code('pages = extract_pages(pdf_path)')
    add_code('chunks = chunk_text(pages, source=source, chunk_size=300, overlap=50)')
    add_code('store.add_chunks(chunks)')
    add_text('What to say out loud: “This is where the indexing begins. We are turning raw PDF pages into chunk objects that can be embedded and searched.”')
    add_text('Point to: src/main.py, index_pdf()')
    story.append(PageBreak())

    add_section('Page 2 — Chunking: this is where "retrievable units" are created')
    add_text('Show this live in src/chunker.py. This is the exact place where a long page gets broken into smaller chunks with overlap.')
    add_code('for page in pages:')
    add_code('    words = page["text"].split()')
    add_code('    end = start + chunk_size')
    add_code('    chunk_words = words[start:end]')
    add_code('    chunk_str = " ".join(chunk_words)')
    add_code('    chunks.append({')
    add_code('        "text": chunk_str,')
    add_code('        "page": page["page"],')
    add_code('        "chunk_id": chunk_id,')
    add_code('    })')
    add_code('    start = end - overlap')
    add_text('What to say out loud: “Notice the overlap. If we only split without overlap, an important fact can be cut across boundary lines. Overlap reduces that risk.”')
    add_text('This is the code-level equivalent of SentenceSplitter in the notebook.')
    story.append(PageBreak())

    add_section('Page 3 — Embeddings: where the vectors are created')
    add_text('Show this live in src/vector_store.py. This is the exact place where Chroma is configured and the embedding model is declared.')
    add_code('self.embedding_fn = embedding_functions.SentenceTransformerEmbeddingFunction(')
    add_code('    model_name="all-MiniLM-L6-v2"')
    add_code(')')
    add_code('self.collection = self.client.get_or_create_collection(')
    add_code('    name=collection_name,')
    add_code('    embedding_function=self.embedding_fn,')
    add_code('    metadata={"hnsw:space": "cosine"},')
    add_code(')')
    add_text('What to say out loud: “This is the exact embedding step. Each chunk is converted to a vector and stored in the database.”')
    add_text('This replaces the notebook’s HuggingFaceEmbedding / LlamaIndex abstraction with explicit embedding logic in Python.')
    story.append(PageBreak())

    add_section('Page 4 — Storage: how Chroma stores document metadata')
    add_text('Show this live in src/vector_store.py, add_chunks(). This is where metadata is attached to each chunk. That metadata matters later for page references, source tracking, and citation.')
    add_code('self.collection.add(')
    add_code('    ids=[f"{c[\'source\']}::{c[\'chunk_id\']}" for c in chunks],')
    add_code('    documents=[c["text"] for c in chunks],')
    add_code('    metadatas=[')
    add_code('        {')
    add_code('            "page": c["page"],')
    add_code('            "source": c["source"],')
    add_code('            "chunk_id": c["chunk_id"],')
    add_code('        }')
    add_code('        for c in chunks')
    add_code('    ],')
    add_code(')')
    add_text('What to say out loud: “This is not just raw text storage. We are storing file source, page number, and chunk identity so we can cite the evidence later.”')
    story.append(PageBreak())

    add_section('Page 5 — Retrieval: this is the real vector-search step')
    add_text('Show this live in src/vector_store.py, query_with_candidates(). This is the exact analog of the notebook’s query engine.')
    add_code('results = self.collection.query(query_texts=[question], n_results=fetch_k, where=where)')
    add_code('for rank, (text, meta, dist) in enumerate(')
    add_code('    zip(results["documents"][0], results["metadatas"][0], results["distances"][0]), start=1')
    add_code('):')
    add_code('    candidates.append({')
    add_code('        "text": text,')
    add_code('        "page": meta["page"],')
    add_code('        "source": meta["source"],')
    add_code('        "distance": dist,')
    add_code('        "confidence": 1 - (dist / 2),')
    add_code('        "rank": rank,')
    add_code('    })')
    add_text('What to say out loud: “This is the retrieval step. We ask the vector DB for the most similar chunks, rank them by distance, and compute a confidence score. This is exactly what the query engine does under the hood in the notebook.”')
    story.append(PageBreak())

    add_section('Page 6 — Prompting + tool use: where the model decides whether to call a tool')
    add_text('Show this live in src/rag.py. This is the most important conceptual link to the notebook’s query engine and tool-calling idea.')
    add_code('SYSTEM_PROMPT = """You are a helpful research assistant and teacher with two tools:')
    add_code('- search_documents: searches the user\'s uploaded PDF documents.')
    add_code('- web_search: searches the live internet.')
    add_code('...')
    add_code('"""')
    add_code('TOOLS_SCHEMA = [')
    add_code('    {"name": "search_documents", ...},')
    add_code('    {"name": "web_search", ...},')
    add_code(']')
    add_text('What to say out loud: “This is the policy layer. The model is told: document first, web as fallback, do not loop endlessly, and do not invent facts. The notebook may have hidden this in the framework, but here it is explicit in code.”')
    story.append(PageBreak())

    add_section('Page 7 — The confidence gate: code-level safeguard against bad retrieval')
    add_text('Show this live in src/rag.py. This is where we stop an answer from being based on weak document match quality.')
    add_code('if gate_state["web_called"] or not web_enabled or confidence >= threshold:')
    add_code('    return "", []')
    add_code('results = _web_search(query_text, max_results=5, allowed_domains=allowed_domains, blocked_domains=blocked_domains)')
    add_code('gate_state["web_called"] = True')
    add_code('gate_state["auto_triggered"] = True')
    add_text('What to say out loud: “This is the fix for the bad behavior we saw earlier. The model is not allowed to rely only on weak document similarity if the confidence is low. The code forces a web fallback instead of letting the system guess.”')
    story.append(PageBreak())

    add_section('Page 8 — Document-first policy: the exact safeguard to teach students')
    add_text('This is the key rule that should be emphasized. Show the SYSTEM_PROMPT block from src/rag.py and explain that it sets behavior, not just response style.')
    add_code('Document-first policy: always search_documents first for questions that could be answered from the indexed PDFs.')
    add_code('Never use web_search before search_documents when the document corpus could plausibly answer the question.')
    add_code('Use web_search only as a fallback for missing facts, current information, dates, names, places, events, or if the document search returns no useful result.')
    add_text('What to say out loud: “This is the entire principle behind the app. We do not let the web bypass the document corpus when the document corpus could answer the question.”')
    story.append(PageBreak())

    add_section('Page 9 — Provider switching: the model layer is configurable, not hard-coded')
    add_text('Show this live in src/llm_config.py. This is the exact point where the app decides which provider is active and which model is chosen.')
    add_code('raw_active_provider = (os.environ.get("ACTIVE_PROVIDER") or "").strip().lower()')
    add_code('if raw_active_provider in {"groq", "claude", "huggingface", "gemini", "openrouter"}:')
    add_code('    provider = raw_active_provider')
    add_code('if provider == "openrouter":')
    add_code('    return LLMSettings(')
    add_code('        name="openrouter",')
    add_code('        model=os.environ.get("OPENROUTER_MODEL") or "openai/gpt-oss-20b:free",')
    add_code('        api_key=os.environ.get("OPENROUTER_API_KEY"),')
    add_code('    )')
    add_text('What to say out loud: “This is where the app becomes portable. We are not mixing logic for every provider in the RAG flow itself. The provider selection is centralized in config.”')
    story.append(PageBreak())

    add_section('Page 10 — Live demo checklist for the instructor')
    add_bullet('Open src/main.py and show index_pdf()')
    add_bullet('Open src/chunker.py and highlight the overlap logic')
    add_bullet('Open src/vector_store.py and highlight SentenceTransformerEmbeddingFunction and collection.add()')
    add_bullet('Open src/vector_store.py and show query_with_candidates()')
    add_bullet('Open src/rag.py and highlight SYSTEM_PROMPT and the document-first policy')
    add_bullet('Open src/rag.py and show the confidence gate')
    add_bullet('Open src/app.py and show the Streamlit UI controls')
    add_text('This is not a conceptual summary slide. This is the exact execution order to follow live so students see the full RAG pipeline in real code.')

    doc.build(story)


if __name__ == '__main__':
    out_path = 'Day4_RAG_Code_Breakdown.pdf'
    build_pdf(out_path)
    print(f'Generated PDF: {out_path}')
